app:
  kafka:
    topics:
      games: "games.game-finished.test" # Es buena práctica usar nombres distintos en tests
      bet-settled: "bets.bet-settled.test"

spring:
  kafka:
    producer:
#      transaction-id-prefix: tx-
      properties:
        spring.json.add.type.headers: true
    consumer:
      properties:
        spring.json.trusted.packages: "com.bjpractice.events,com.bjpractice.bets.kafka.event"