server:
  port: 8082

spring:
  application:
    name: bets

  datasource:
    url: jdbc:mysql://localhost:3306/bets_db?serverTimezone=UTC
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  # --- CONFIGURACIÓN DE KAFKA ---
  kafka:
    # --- Configuración del Consumidor  ---
    consumer:
      bootstrap-servers: localhost:9092
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.bjpractice.bets.kafka.event"
        spring.json.use.type.headers: false

        spring.json.value.default.type: com.bjpractice.bets.kafka.event.GameFinishedEvent

    # --- Configuración del Productor  ---
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# --- Propiedades personalizadas de la aplicación (incluyendo topics) ---
app:
  kafka:
    topics:
      game-finished: "games.game-finished" # Topic del que se leen los resultados
      bet-settled: "bets.bet-settled"