# 1. Configuración del servidor para auth-service
server:
  port: 8084 # Puerto para el servicio de autenticación (actualizado)

# 2. Identificación de la aplicación
spring:
  application:
    name: auth-service

# 3. Propiedades personalizadas para la configuración de JWT
jwt:
  # La clave secreta para firmar los tokens.
  secret: "${JWT_SECRET:c3VwZXItc2VjcmV0LWtleS1mb3ItZGV2ZWxvcG1lbnQtZW52aXJvbm1lbnQ=}"

  # Tiempo de expiración del token en milisegundos.
  expiration: 86400000 # 24 horas
application:
  config:
    # URL para el Feign Client que se conecta con user-service.
    # Lee la variable de entorno USER_SERVICE_URL (para Docker)
    # y si no existe, usa un valor por defecto (para desarrollo local).
    user-service-url: "${USER_SERVICE_URL:http://localhost:8083}"