app:
  kafka:
    topics:
      # Se sobreescribe el nombre del topic para aislar los tests
      games: "games.game-finished.test"

spring:
  kafka:
    consumer:
      properties:
        # Aseguramos que en los tests también se confíe en los paquetes correctos
        spring.json.trusted.packages: "com.bjpractice.events,com.bjpractice.game_core.kafka.event"