server:
  port: 8081

spring:
  application:
    name: game-core

  # --- Configuración de la Base de Datos (DataSource) ---
  datasource:
    url: jdbc:mysql://localhost:3306/game_core_db?serverTimezone=UTC
    username: root
    password: root

  # --- Configuración de JPA / Hibernate ---
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  # --- Kafka config (Producer) ---
  kafka:
    producer:
      # CORRECCIÓN: Todas estas propiedades deben estar al mismo nivel de indentación.
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: gameFinished:com.bjpractice.game_core.kafka.event.GameFinishedEvent,playerDoubledDown:com.bjpractice.game_core.kafka.event.PlayerDoubledDownEvent

kafka:
  topic:
    games: "games"