spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

  kafka:
    # El productor del test ahora enviará los mensajes con la "etiqueta" de tipo,
    # solucionando la SerializationException.
    producer:
      properties:
        spring.json.add.type.headers: true

    # El consumidor del test también confía en las etiquetas.
    consumer:
      properties:
        spring.json.trusted.packages: "com.bjpractice.events"

# Usamos topics con sufijo ".test" para aislar las pruebas.
app:
  kafka:
    topics:
      bet-settled: "bets.bet-settled.test"